FROM php:8.2-apache

# Enable mod_rewrite
RUN a2enmod rewrite

# Install MySQL extension
RUN docker-php-ext-install pdo pdo_mysql

# Copy all files to Apache root
COPY . /var/www/html/

# Set correct permissions
RUN chown -R www-data:www-data /var/www/html

EXPOSE 80